services:
  backend:
    container_name: rest-api-service
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev:container
    volumes:
      - .:/usr/src/app/
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14.4-alpine3.16
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
